# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - build
  - commit:analysis

build:
  stage: build
  image: node:12.18
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo "Start building App"
    - echo $CI_REGISTRY_IMAGE
    - npm install
    - echo "Build successfully!"


include:
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"

artifacts:
  reports:
    secret_detection

.secret-analyzer:
  stage: commit:analysis
  needs: []

