# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: node:latest
cache:
  paths:
  - node_modules/
stages:
- build
- commit:analysis
- test
build:
  stage: build
  image: node:12.18
  variables:
    IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  script:
  - echo "Start building App"
  - echo $CI_REGISTRY_IMAGE
  - npm install
  - echo "Build successfully!"
include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: 'true'
artifacts:
  reports: secret_detection
".secret-analyzer":
  stage: commit:analysis
  needs: []
sast:
  stage: test
